### ISSUE TITLE
iteminfo command

### ISSUE THREAD

**Issue by ha6000** [Saikou-Bot/SaikouBotV2#158]
### Suggestion by cow
Command like `gameinfo` but for catalog items
#### ToDo
- [x] Implement catalog search endpoint in roblox wrapper
- [ ] Scrape the item's catalog page
- [ ] Create iteminfo command
